// Code Generated by Sidekick is for learning and experimentation purposes only.
public class Calculator {

    public int add(int a, int b) {
        return a + b;
    }

    public int subtract(int a, int b) {
        return a - b;
    }

    public int multiply(int a, int b) {
        return a * b;
    }

    public double divide(int a, int b) {
        if (b == 0) {
            throw new IllegalArgumentException("Cannot divide by zero");
        }
        return (double) a / b;
    }

    public static void main(String[] args) {
        Calculator calc = new Calculator();

        int x = 10;
        int y = 5;

        System.out.println("Add: " + calc.add(x, y));
        System.out.println("Subtract: " + calc.subtract(x, y));
        System.out.println("Multiply: " + calc.multiply(x, y));
        System.out.println("Divide: " + calc.divide(x, y));
    }
}
